export const collectionsData = {
  collections: [
    {
      id: "1",
      title: "Summer Collection",
      description: "Light and breezy pieces for the summer season",
      image:
        "/images/willDelete/collections/81v3DF-jGjL._AC_SL1500_-removebg-preview.png",
      price: 1750.0,
      products: [
        {
          id: "1",
          title: "Plastic Dining Armchair",
          image: "/images/willdelete/product-14-13_788x1013  (2).png",
          price: 200.0,
          colors: ["#007F7F", "#000000", "#FFFF00"],
          offer: 0.4,
          quantity: 200,
          rate: 4.5,
        },
        {
          id: "2",
          title: "Modern White Chair",
          image: "/images/willdelete/product-14-13_788x1013 .png",
          price: 260.0,
          colors: [],
          offer: 0.07,
          quantity: 150,
          rate: 4.0,
        },
        {
          id: "3",
          title: "Red Sacrificial Chair",
          image: "/images/willdelete/product-14-13_788x1013 (7).png",
          price: 170.0,
          colors: ["#800000", "#000000", "#FFFFFF"],
          offer: 0.2,
          quantity: 80,
          rate: 4.0,
        },
        {
          id: "4",
          title: "Gray Lounge Chair",
          image: "/images/willdelete/product-14-13_788x1013 (6).png",
          price: 180.0,
          colors: [],
          offer: 0.1,
          quantity: 60,
          rate: 4.0,
        },
      ],
    },
    {
      id: "2",
      title: "Autumn Essentials",
      description: "Cozy and stylish autumn wear",
      image:
        "/images/willDelete/collections/zestaw-mebli-balkonowych-5895-stolik-2x-krzeslo-czarne.jpg",
      price: 960.0,
      products: [
        {
          id: "5",
          title: "Dark Gray Dining Chair",
          image: "/images/willdelete/11_700x900.png",
          price: 170.0,
          colors: [],
          offer: 0.15,
          quantity: 100,
          rate: 3.5,
        },
        {
          id: "6",
          title: "Modern Black Chair",
          image: "/images/willdelete/product-14-13_788x1013 (3).png",
          price: 100.0,
          colors: ["#000000", "#DDDDDD"],
          offer: 0.44,
          quantity: 50,
          rate: 3.0,
        },
      ],
    },
    {
      id: "3",
      title: "Winter Comforts",
      description: "Koma and Torus are two tea infusers, each with an original design and a concealed function. Koma has a round base and a long stainless steel-trimmed handle which offers a comfortable grip and allows for easy pouring. Torus has a round base and a short handle, which makes it easy to hold and pour. Both infusers are made of stainless steel and have a silicone base that prevents them from slipping on the table.",
      image: "/images/willDelete/collections/collection.png",
      price: 1200.0,
      products: [
        {
          id: "7",
          title: "Black Table Lamp",
          image: "/images/willdelete/product-14-13_788x1013 (4).png",
          price: 140.0,
          colors: ["#000000", "#FFFF00", "#FFFFFF"],
          offer: 0,
          quantity: 120,
          rate: 5.0,
        },
        {
          id: "8",
          title: "Stylish Travel Backpack",
          image: "/images/willdelete/product-14-13_788x1013 (5).png",
          price: 130.0,
          colors: [
            "#0000FF",
            "#000000",
            "#888888",
            "#0000FF",
            "#000000",
            "#888888",
          ],
          offer: 0,
          quantity: 0,
          rate: 4.5,
        },
        {
          id: "9",
          title: "Minimalist Wall Clock",
          image:
            "/images/willdelete/11_63e20b3b-21f2-49ff-93f8-2179551f43e0_700x900.png",
          price: 90.0,
          colors: ["#FFFFFF", "#000000", "#D3D3D3"],
          offer: 0.1,
          quantity: 70,
          rate: 4.3,
        },
      ],
    },
  ],
};
